management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: @project.name@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

logging:
  level:
    com.Kiiko.ExhibitionsApp.controller: debug

server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Exhibition_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true