management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.Kiiko.ExhibitionsApp.controller: debug

server:
  error:
    include-message: always